name: release npm package
on:
  push:
    branches:
      - main
jobs:
  auto-release:
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          # ãƒã‚¤ãƒ³ãƒˆ1
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set releaser settings
        run: |
          git config --global user.name github-action
          git config --global user.email kcattdev@gmail.com

      - name: Set .npmrc
        # ãƒã‚¤ãƒ³ãƒˆ2
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc

      - run: yarn install --immutable --immutable-cache --check-cache

      - name: Major release
        id: major
        run: yarn lib release-it --npm.publishArgs='--registry=https://registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' major --ci
        if: contains(toJSON(github.event.commits.*.message), 'ğŸš€ bump up version major')

      - name: Minor release
        id: minor
        run: yarn lib release-it --npm.publishArgs='--registry=https://registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' minor --ci
        if: steps.major.conclusion == 'skipped' && contains(toJSON(github.event.commits.*.message), 'ğŸš€ bump up version minor')

      - name: Patch release
        # ãƒã‚¤ãƒ³ãƒˆ3
        run: yarn lib release-it --npm.publishArgs='--registry=https://registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' patch --ci
        # ãƒã‚¤ãƒ³ãƒˆ4
        if: "!(steps.major.conclusion == 'success' || steps.minor.conclusion == 'success')"
